In [32]:
import pandas as pd

In [33]:
dataset = pd.read_csv('/content/heart_disease_data.csv')

In [34]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [35]:
dataset.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [36]:
dataset.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [37]:
dataset.shape

(303, 14)

In [ ]:
dataset.isnull().sum()

In [39]:
num_col = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
cat_col = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

In [51]:
# Standardization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_col_standardized = scaler.fit_transform(dataset[num_col])

In [52]:
num_col_standardized = pd.DataFrame(num_col_standardized)

In [53]:
num_col_standardized.columns = dataset[num_col].columns

In [ ]:
num_col_standardized

In [55]:
dataset_standardized = pd.concat([num_col_standardized, dataset[cat_col]], axis=1)

In [56]:
dataset_standardized.head()

age  trestbps      chol   thalach   oldpeak  sex  cp  fbs  restecg  \
0  0.952197  0.763956 -0.256334  0.015443  1.087338    1   3    1        0   
1 -1.915313 -0.092738  0.072199  1.633471  2.122573    1   2    0        1   
2 -1.474158 -0.092738 -0.816773  0.977514  0.310912    0   1    0        0   
3  0.180175 -0.663867 -0.198357  1.239897 -0.206705    1   1    0        1   
4  0.290464 -0.663867  2.082050  0.583939 -0.379244    0   0    0        1   

   exang  slope  ca  thal  
0      0      0   0     1  
1      0      0   0     2  
2      0      2   0     2  
3      0      2   0     2  
4      1      2   0     2

In [57]:
X = dataset_standardized
y = dataset.target

In [ ]:
X.head()

In [ ]:
y.head()

In [61]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=78)

In [62]:
X.shape, X_train.shape, X_test.shape

((303, 13), (242, 13), (61, 13))

In [ ]:
X_train.head()

In [65]:
# Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [67]:
models = [LogisticRegression(), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [70]:
from sklearn.metrics import accuracy_score
def model_test(models):
  for model in models:
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    accuracy = accuracy_score(pred, y_test)
    print(f'Accuracy of {model}:', accuracy)


In [71]:
model_test(models)

Accuracy of LogisticRegression(): 0.8688524590163934
Accuracy of SVC(kernel='linear'): 0.8688524590163934
Accuracy of KNeighborsClassifier(): 0.8360655737704918
Accuracy of RandomForestClassifier(): 0.9016393442622951


In [72]:
# Cross Validation
from sklearn.model_selection import cross_val_score
cv_score_lr = cross_val_score(LogisticRegression(), X, y, cv=5)

In [73]:
cv_score_lr

array([0.81967213, 0.8852459 , 0.85245902, 0.86666667, 0.75      ])

In [77]:
mean_score_lr = sum(cv_score_lr)/len(cv_score_lr)

In [78]:
mean_score_lr

0.834808743169399

In [79]:
def model_test_cv(models):
  for model in models:
    cv_scores = cross_val_score(model, X, y, cv=5)
    mean_cv_score = sum(cv_scores)/len(cv_scores)
    print(f'CV Score of {model}:', mean_cv_score)

In [80]:
model_test_cv(models)

CV Score of LogisticRegression(): 0.834808743169399
CV Score of SVC(kernel='linear'): 0.8283060109289618
CV Score of KNeighborsClassifier(): 0.7953551912568306
CV Score of RandomForestClassifier(): 0.8281967213114754


In [81]:
my_model = RandomForestClassifier()

my_model.fit(X_train, y_train)
prediction = my_model.predict(X_test)
accuracy = accuracy_score(y_test, prediction)

print('Accuracy:', accuracy)

Accuracy: 0.9016393442622951


In [84]:
import numpy
input = [0.290464,	-0.663867,	2.082050,	0.583939,	-0.379244,	0,	0,	0,	1,	1,	2,	0,	2,]
input_array = numpy.asarray(input)
input_reshaped = input_array.reshape((1, -1))

In [85]:
input_reshaped

array([[ 0.290464, -0.663867,  2.08205 ,  0.583939, -0.379244,  0.      ,
         0.      ,  0.      ,  1.      ,  1.      ,  2.      ,  0.      ,
         2.      ]])

In [86]:
pred = my_model.predict(input_reshaped)
pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])